name: Node.js CI

on: [push]

jobs:

  build-api:
    runs-on: ubuntu-latest
    env:
      IDEA_IPFS_HTTP: /ip4/127.0.0.1/tcp/5002/http
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and run IPFS daemon
      run: |
        npm i -g node-pre-gyp ipfs
        jsipfs daemon &
    - run: npm ci
      working-directory: ./packages/idea-api
    - run: npm test
      working-directory: ./packages/idea-api

  build-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./packages/idea-cli
    - run: npm test
      working-directory: ./packages/idea-cli

  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./packages/idea-web
    - run: npm test
      working-directory: ./packages/idea-web
